name: dl-cv
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - six
  - pytorch>=1.6.0
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - matplotlib
  - pillow
  - scikit-image
  - piq=0.5.2