name: dl-cv2
channels:
  - pytorch
  - conda-forge
  - photosynthesis-team
  - defaults
dependencies:
  - python=3.6
  - p
  - six
  - pytorch>=1.6.0
  - torchvision
  - torchaudio
  - cudatoolkit=10.2
  - matplotlib
  - pillow
  - scikit-image
  - piq
  - tqdm
  - cupy
  - scipy
  - requests
  - opencv
